CATALOG_BUILD = true
VERSION = '1.1.0' .. (CATALOG_BUILD and 'c' or 'i')
SCOREBOARDS_ENABLED = CATALOG_BUILD

SCREEN_WIDTH, SCREEN_HEIGHT = playdate.display.getSize()
SIDEBAR_WIDTH = 52
MOON_DISTANCE_FROM_EARTH = 75
MAX_RAMP_UP_DIFFICULTY = 120
MIN_RAMP_UP_DIFFICULTY = 40
